// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/courses": {
            "get": {
                "description": "Возвращает полный список курсов со всеми метаданными.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Content"
                ],
                "summary": "ADMIN: Список всех курсов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Course"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Создает карточку курса с загрузкой изображения. Доступно только администратору.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Content"
                ],
                "summary": "ADMIN: Создание нового курса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название курса",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Описание курса",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "Флаг основного курса (true/false)",
                        "name": "is_main",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Изображение обложки курса",
                        "name": "image_file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "id курса",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error: Ошибка валидации",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/courses/{id}/settings": {
            "put": {
                "description": "Позволяет изменить параметры курса, обложку и статус.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Content"
                ],
                "summary": "ADMIN: Обновление настроек курса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID курса",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Новое название",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Новое описание",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "Тип курса",
                        "name": "is_main",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Статус: draft, active, archived",
                        "name": "status",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "Наличие ДЗ",
                        "name": "has_homework",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "Обязательность ДЗ",
                        "name": "is_homework_mandatory",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "Обязательность тестов",
                        "name": "is_test_mandatory",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "Обязательность проектов",
                        "name": "is_project_mandatory",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "Обязательность Discord",
                        "name": "is_discord_mandatory",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "Запрет копирования",
                        "name": "is_anti_copy_enabled",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Новая обложка",
                        "name": "cover_image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status: updated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error: internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/courses/{id}/stats": {
            "get": {
                "description": "Возвращает агрегированные данные: кол-во учеников, средний балл и т.д.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Stats"
                ],
                "summary": "ADMIN: Статистика курса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID курса",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AdminCourseStats"
                        }
                    }
                }
            }
        },
        "/admin/courses/{id}/structure": {
            "get": {
                "description": "Возвращает иерархическую структуру: Курс -\u003e Модули -\u003e Уроки.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Content"
                ],
                "summary": "ADMIN: Содержание курса (Дерево)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID курса",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CourseStructure"
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/courses/{id}/students": {
            "get": {
                "description": "Возвращает список всех учеников с их текущим прогрессом на курсе.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Users"
                ],
                "summary": "ADMIN: Список учеников курса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID курса",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.AdminStudentProgress"
                            }
                        }
                    }
                }
            }
        },
        "/admin/enroll": {
            "post": {
                "description": "Привязывает ученика к конкретному курсу.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Users"
                ],
                "summary": "ADMIN: Запись на курс",
                "parameters": [
                    {
                        "description": "Связка UserID и CourseID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.EnrollRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status: enrolled",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/lessons": {
            "post": {
                "description": "Создает урок с загрузкой видео и презентации в S3.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Content"
                ],
                "summary": "ADMIN: Добавление урока",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID модуля",
                        "name": "module_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID преподавателя",
                        "name": "teacher_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название урока",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Порядковый номер",
                        "name": "order_num",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "HTML/JSON контент урока",
                        "name": "content_text",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Видео файл (до 500MB)",
                        "name": "video_file",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Файл презентации",
                        "name": "presentation_file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/modules": {
            "post": {
                "description": "Добавляет модуль в учебный план курса.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Content"
                ],
                "summary": "ADMIN: Создание модуля",
                "parameters": [
                    {
                        "description": "Данные модуля",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateModuleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/projects": {
            "post": {
                "description": "Создает финальный проект и привязывает его к уроку.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Content"
                ],
                "summary": "ADMIN: Добавление проекта",
                "parameters": [
                    {
                        "description": "Данные проекта",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/tests": {
            "post": {
                "description": "Создает тест и привязывает его к уроку.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Content"
                ],
                "summary": "ADMIN: Добавление теста",
                "parameters": [
                    {
                        "description": "Данные теста",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateTestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "post": {
                "description": "Создает аккаунт для ученика, учителя, родителя или куратора.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Users"
                ],
                "summary": "ADMIN: Создание пользователя",
                "parameters": [
                    {
                        "description": "Данные пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Ввод email и пароля, возвращает HTTP-Only Cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Аутентификация"
                ],
                "summary": "Вход в систему (Log in student/admin)",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: Login successful, user: {...}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "error: Неправильный логин/пароль",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Данный функционал отключен, пользователи создаются только Администратором.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Аутентификация"
                ],
                "summary": "Регистрация (ЗАБЛОКИРОВАНО)",
                "responses": {
                    "403": {
                        "description": "error: Public registration is disabled.",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/dashboard/home": {
            "get": {
                "description": "Returns the home dashboard for the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get user home dashboard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AdminCourseStats": {
            "type": "object",
            "properties": {
                "average_score": {
                    "type": "number"
                },
                "frozen_students": {
                    "type": "integer"
                },
                "graduated_students": {
                    "type": "integer"
                },
                "new_students_month": {
                    "type": "integer"
                },
                "success_rate_breakdown": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "total_students": {
                    "type": "integer"
                }
            }
        },
        "domain.AdminStudentProgress": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "homeworks_done": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "lessons_attended": {
                    "type": "integer"
                },
                "photo_url": {
                    "type": "string"
                },
                "progress_percent": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.Course": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "has_homework": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "is_anti_copy_enabled": {
                    "type": "boolean"
                },
                "is_discord_mandatory": {
                    "type": "boolean"
                },
                "is_homework_mandatory": {
                    "type": "boolean"
                },
                "is_main": {
                    "type": "boolean"
                },
                "is_project_mandatory": {
                    "type": "boolean"
                },
                "is_test_mandatory": {
                    "type": "boolean"
                },
                "status": {
                    "$ref": "#/definitions/domain.CourseStatus"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.CourseStatus": {
            "type": "string",
            "enum": [
                "draft",
                "active",
                "archived"
            ],
            "x-enum-varnames": [
                "CourseStatusDraft",
                "CourseStatusActive",
                "CourseStatusArchived"
            ]
        },
        "domain.CourseStructure": {
            "type": "object",
            "properties": {
                "course": {
                    "$ref": "#/definitions/domain.Course"
                },
                "modules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ModuleStructure"
                    }
                }
            }
        },
        "domain.Lesson": {
            "type": "object",
            "properties": {
                "content_text": {
                    "type": "string"
                },
                "duration_min": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "is_published": {
                    "type": "boolean"
                },
                "lesson_time": {
                    "type": "string"
                },
                "module_id": {
                    "type": "string"
                },
                "order_num": {
                    "type": "integer"
                },
                "presentation_url": {
                    "type": "string"
                },
                "teacher_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "video_url": {
                    "type": "string"
                }
            }
        },
        "domain.Module": {
            "type": "object",
            "properties": {
                "course_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "order_num": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.ModuleStructure": {
            "type": "object",
            "properties": {
                "lessons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Lesson"
                    }
                },
                "module": {
                    "$ref": "#/definitions/domain.Module"
                }
            }
        },
        "domain.Role": {
            "type": "string",
            "enum": [
                "student",
                "parent",
                "teacher",
                "moderator",
                "curator",
                "admin"
            ],
            "x-enum-varnames": [
                "RoleStudent",
                "RoleParent",
                "RoleTeacher",
                "RoleModerator",
                "RoleCurator",
                "RoleAdmin"
            ]
        },
        "http.CreateModuleRequest": {
            "type": "object",
            "properties": {
                "course_id": {
                    "type": "string",
                    "example": "c1111111-1111-1111-1111-111111111111"
                },
                "description": {
                    "type": "string",
                    "example": "Типы данных, переменные, циклы"
                },
                "order_num": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "Основы синтаксиса"
                }
            }
        },
        "http.CreateProjectRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Разработка API на Go"
                },
                "lesson_id": {
                    "type": "string",
                    "example": "l2222222-2222-2222-2222-222222222222"
                },
                "max_score": {
                    "type": "integer",
                    "example": 100
                },
                "title": {
                    "type": "string",
                    "example": "Финальный проект"
                }
            }
        },
        "http.CreateTestRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Тест на проверку базовых знаний Go"
                },
                "lesson_id": {
                    "type": "string",
                    "example": "l2222222-2222-2222-2222-222222222222"
                },
                "passing_score": {
                    "type": "integer",
                    "example": 70
                },
                "title": {
                    "type": "string",
                    "example": "Итоговый тест по модулю 1"
                }
            }
        },
        "http.CreateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "student@test.kz"
                },
                "first_name": {
                    "type": "string",
                    "example": "Иван"
                },
                "last_name": {
                    "type": "string",
                    "example": "Иванов"
                },
                "password": {
                    "type": "string",
                    "example": "secret123"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.Role"
                        }
                    ],
                    "example": "student"
                }
            }
        },
        "http.EnrollRequest": {
            "type": "object",
            "properties": {
                "course_id": {
                    "type": "string",
                    "example": "c1111111-1111-1111-1111-111111111111"
                },
                "user_id": {
                    "type": "string",
                    "example": "a0000000-0000-0000-0000-000000000001"
                }
            }
        },
        "http.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Cap Education LMS - API",
	Description:      "API для LMS платформы Cap Education.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
